# Generated by Django 2.2.4 on 2019-08-28 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
