# Generated by Django 2.2.4 on 2019-08-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0002_delete_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=50)),
                ('property_name', models.CharField(choices=[('Kwabenya 1 Storey House', 'Kwabenya 1 Storey House')], max_length=50)),
                ('room_types', models.CharField(choices=[('Single Room Self Contained', 'Single Room Self Contained'), ('Two Bed Room Self Contained', 'Two Bed Room Self Contained'), ('Three Bed Room Self Contained', 'Three Bed Room Self Contained')], max_length=50)),
                ('duration_from', models.DateField()),
                ('duration_to', models.DateField()),
                ('deposit_amt', models.FloatField(default='0')),
            ],
        ),
    ]
