# Generated by Django 2.2.4 on 2019-08-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rent_per_month',
            field=models.FloatField(default='0'),
        ),
        migrations.AddField(
            model_name='rent',
            name='total_rent',
            field=models.FloatField(default='0'),
        ),
    ]
