# Generated by Django 2.2.4 on 2019-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20190829_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='duration_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='duration_to',
            field=models.DateField(),
        ),
    ]
