# Generated by Django 2.2.4 on 2019-08-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_auto_20190829_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='duration_from',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rent',
            name='duration_to',
            field=models.CharField(max_length=50),
        ),
    ]
