# Generated by Django 2.2.4 on 2019-08-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20190831_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='duration_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='duration_to',
            field=models.DateTimeField(),
        ),
    ]
