# Generated by Django 2.2.4 on 2019-09-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_auto_20190831_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='duration_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rent',
            name='duration_to',
            field=models.DateField(),
        ),
    ]
