# Generated by Django 2.2.4 on 2019-08-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('contact_person', models.CharField(max_length=50)),
                ('contact_person_no', models.CharField(max_length=50)),
                ('agent_name', models.CharField(choices=[(1, 'Awudu Baba')], default='', max_length=50)),
                ('property_completion_date', models.DateField()),
                ('cost_of_const', models.FloatField()),
                ('no_of_rooms', models.IntegerField()),
                ('room_types', models.CharField(max_length=50)),
            ],
        ),
    ]
