# Generated by Django 2.2.4 on 2019-08-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_list',
            name='room_types',
            field=models.CharField(default='', max_length=50),
        ),
    ]
