# Generated by Django 2.2.4 on 2019-08-27 16:11

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20190827_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_list',
            name='room_types',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
