# Generated by Django 2.2.4 on 2019-08-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20190827_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_list',
            name='care_taker',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='property_list',
            name='room_types',
            field=models.CharField(choices=[(2, 'Single Room Self Contained'), (3, 'Two Bed Room Self Contained'), (4, 'Three Bed Room Self Contained')], default='', max_length=50),
        ),
    ]
