# Generated by Django 2.2.4 on 2019-08-28 09:51

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_auto_20190828_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_list',
            name='cost_of_const',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='property_list',
            name='no_of_rooms',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='property_list',
            name='room_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(2, 'Single Room Self Contained'), (3, 'Two Bed Room Self Contained'), (4, 'Three Bed Room Self Contained')], max_length=5),
        ),
    ]
