# Generated by Django 2.2.4 on 2019-08-28 11:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_auto_20190828_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_list',
            name='agent_name',
            field=models.CharField(choices=[('Awudu Baba', 'Awudu Baba')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='property_list',
            name='room_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Single Room Self Contained', 'Single Room Self Contained'), ('Two Bed Room Self Contained', 'Two Bed Room Self Contained'), ('Three Bed Room Self Contained', 'Three Bed Room Self Contained')], max_length=84),
        ),
    ]
