# Generated by Django 2.2.4 on 2019-08-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system_data',
            name='system_data_type',
            field=models.CharField(choices=[('101', 'Expenditure Groups'), ('102', 'Building Type'), ('103', 'Room Types'), ('', '')], default='', max_length=10),
        ),
    ]
