# Generated by Django 2.2.4 on 2019-09-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expenditure_date', models.DateField()),
                ('expenditure_purpose', models.CharField(max_length=50)),
                ('expenditure_beneficiary', models.CharField(max_length=50)),
                ('expenditure_amount', models.CharField(max_length=50)),
                ('expenditure_amount_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenditure_group_no', models.CharField(choices=[('Building Maintenance', 'Building Maintenance')], max_length=10)),
            ],
        ),
    ]
