# Generated by Django 2.2.4 on 2019-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_data_head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_code', models.CharField(max_length=50)),
                ('head_title', models.CharField(max_length=50)),
            ],
        ),
    ]
